import { IPropsData } from "./interface";

export const data: IPropsData[] = [
  {
    title: "Graphic Design Workshop",
    description: "Enhance your graphic design skills and stay updated with the latest trends in this workshop.",
    event_date: "2024-07-20",
    organizer: "GraphicMasters Design School",
  },
  {
    title: "Digital Marketing Seminar",
    description: "Discover the most effective digital marketing strategies in this practical seminar.",
    event_date: "2024-08-05",
    organizer: "MarketBoost Marketing Agency",
  },
  {
    title: "Mobile App Development Course",
    description: "Learn the latest technologies and tools for mobile app development in this course.",
    event_date: "2024-09-15",
    organizer: "MobileDev Educational Center",
  },
  {
    title: "Entrepreneurship Forum",
    description: "Discuss key aspects of entrepreneurship and gain insights from leading experts in this forum.",
    event_date: "2024-10-10",
    organizer: "EntrepreneursUnited Business Association",
  },
  {
    title: "Classical Music Concert",
    description: "Enjoy the performances of talented musicians in the finest classical music pieces.",
    event_date: "2024-11-25",
    organizer: "National Philharmonic Orchestra",
  },
  {
    title: "Leadership Training",
    description: "Develop your leadership and management skills in this intensive training.",
    event_date: "2024-07-30",
    organizer: "LeadNow Leadership Development Center",
  },
  {
    title: "Startup Workshop",
    description: "Learn how to start and grow your own startup successfully in this workshop.",
    event_date: "2024-08-15",
    organizer: "StartupHub Startup Incubator",
  },
  {
    title: "Innovation Conference",
    description: "Explore the latest innovative technologies and approaches in this conference.",
    event_date: "2024-09-30",
    organizer: "InnovateTech Innovation Institute",
  },
  {
    title: "Photography Masterclass",
    description: "Enhance your photography skills and learn about creative approaches in this masterclass.",
    event_date: "2024-07-10",
    organizer: "ShutterMasters Photography School",
  },
  {
    title: "Web Design Workshop",
    description: "Get hands-on experience and learn the fundamentals of web design in this workshop.",
    event_date: "2024-08-20",
    organizer: "CreativeDesign Web Studio",
  },
  {
    title: "Artificial Intelligence Conference",
    description: "This conference is dedicated to the latest advancements in artificial intelligence.",
    event_date: "2024-09-05",
    organizer: "Artificial Intelligence Institute",
  },
  {
    title: "Cooking Masterclass",
    description: "Discover the secrets of delicious cuisine from our professionals in this masterclass.",
    event_date: "2024-10-25",
    organizer: "Chef's Secrets Culinary School",
  },
  {
    title: "Data Science Bootcamp",
    description: "Gain practical skills in data science and analytics in this intensive bootcamp.",
    event_date: "2024-11-10",
    organizer: "DataLab Analytics Academy",
  },
  {
    title: "Virtual Reality Workshop",
    description: "Explore the world of virtual reality and learn to create immersive experiences in this workshop.",
    event_date: "2024-12-01",
    organizer: "VR Innovations Lab",
  },
  {
    title: "Blockchain Summit",
    description: "Learn about the latest trends and applications of blockchain technology in this summit.",
    event_date: "2024-07-15",
    organizer: "BlockchainX Summit",
  },
  {
    title: "Financial Planning Seminar",
    description: "Get insights into effective financial planning strategies in this informative seminar.",
    event_date: "2024-08-25",
    organizer: "FinancePro Consulting",
  },
  {
    title: "Health and Wellness Retreat",
    description: "Join us for a rejuvenating retreat focused on holistic health and wellness practices.",
    event_date: "2024-09-20",
    organizer: "Wellness Oasis Retreat Center",
  },
  {
    title: "SEO Workshop",
    description: "Learn about search engine optimization techniques and best practices in this workshop.",
    event_date: "2024-10-05",
    organizer: "SEO Masters Academy",
  },
  {
    title: "Public Speaking Training",
    description: "Enhance your public speaking skills and overcome stage fright in this training program.",
    event_date: "2024-11-20",
    organizer: "SpeakWell Public Speaking Institute",
  },
  {
    title: "Machine Learning Bootcamp",
    description: "Gain hands-on experience in machine learning algorithms and applications in this bootcamp.",
    event_date: "2024-12-10",
    organizer: "ML Tech Academy",
  },
  {
    title: "Digital Art Exhibition",
    description: "Experience a showcase of digital art creations by talented artists from around the world.",
    event_date: "2024-07-05",
    organizer: "DigitalArt Gallery",
  },
  {
    title: "UI/UX Design Workshop",
    description: "Learn the principles of user interface and user experience design in this interactive workshop.",
    event_date: "2024-08-30",
    organizer: "DesignUX Studio",
  },
  {
    title: "Environmental Conservation Conference",
    description: "Join us for discussions on environmental issues and strategies for conservation.",
    event_date: "2024-09-10",
    organizer: "GreenEarth Foundation",
  },
  {
    title: "E-commerce Summit",
    description: "Discover the latest trends and innovations in e-commerce at this industry summit.",
    event_date: "2024-10-15",
    organizer: "EcommerceX Summit",
  },
  {
    title: "Fitness Bootcamp",
    description: "Achieve your fitness goals with intensive workouts and personalized training in this bootcamp.",
    event_date: "2024-11-30",
    organizer: "FitLife Fitness Center",
  },
  {
    title: "Creative Writing Workshop",
    description: "Unleash your creativity and improve your writing skills in this engaging workshop.",
    event_date: "2024-12-20",
    organizer: "WriteNow Writing Academy",
  },
  {
    title: "Cybersecurity Conference",
    description: "Stay updated on cybersecurity threats and best practices at this informative conference.",
    event_date: "2024-07-20",
    organizer: "CyberSec Solutions",
  },
  {
    title: "Fashion Design Masterclass",
    description: "Learn about the latest fashion trends and design techniques from industry experts.",
    event_date: "2024-08-10",
    organizer: "FashionX Academy",
  },
  {
    title: "Public Health Symposium",
    description: "Explore key issues in public health and discuss strategies for improving population health.",
    event_date: "2024-09-25",
    organizer: "PublicHealth Initiative",
  },
  {
    title: "Data Visualization Workshop",
    description: "Learn to present data effectively and create compelling visualizations in this workshop.",
    event_date: "2024-10-20",
    organizer: "VisualizeData Institute",
  },
];
